#!/usr/bin/env python3
"""generated_strats.py  --  AUTO-GENERATED by codegen.py. DO NOT EDIT BY HAND.
Position functions translated from to_translate_queue.csv via the hybrid
(template-first, LLM-fallback) codegen step, each validated by the gauntlet.
Single-ticker -> STRATS (df->position). Multi-ticker -> MULTI (returns series).
Research tool, not financial advice."""
import numpy as np, pandas as pd
from strategy_templates import build

# g001  Price Channel Breakout Strategy  (template: donchian_breakout)
_g001 = build('donchian_breakout', {'entry_n': 20, 'exit_n': 20})
def g001(df): return _g001(df)

# g002  Stochastic Slow RSI MACD Strategy  (template: stochastic)
_g002 = build('stochastic', {'k_n': 14, 'lower': 20.0, 'upper': 80.0, 'sma_filter': 0, 'time_stop': 0})
def g002(df): return _g002(df)

# g003  Long-only Momentum Strategy with 200-day SMA Exit  (template: ma_crossover)
_g003 = build('ma_crossover', {'fast': 50, 'slow': 200, 'ma': 'sma'})
def g003(df): return _g003(df)

# g004  8 SMA and 25 SMA Crossover Strategy  (template: ma_crossover)
_g004 = build('ma_crossover', {'fast': 8, 'slow': 25, 'ma': 'sma'})
def g004(df): return _g004(df)

# g005  Dynamic Allocation Strategy (QQQ/BND)  (template: allocation, ['QQQ', 'BND'])
_g005 = build('allocation', {'sma_n': 30, 'on_risk_w': 0.8, 'off_risk_w': 0.2})
def g005(risk, safe): return _g005(risk, safe)

# g006  Linear Regression Mean Reversion Strategy  (template: linreg_mr)
_g006 = build('linreg_mr', {'n': 14, 'sma_filter': 200, 'allow_short': True})
def g006(df): return _g006(df)

# g007  Ray Natio RSI Moving Average Strategy  (template: rsi_meanrev)
_g007 = build('rsi_meanrev', {'rsi_n': 10, 'lower': 30.0, 'upper': 40, 'sma_filter': 200, 'time_stop': 10})
def g007(df): return _g007(df)

# g008  Stochastic K + 200-day SMA Buy Limit Order Strategy  (template: stochastic)
_g008 = build('stochastic', {'k_n': 8, 'lower': 5.0, 'upper': 99, 'sma_filter': 200, 'time_stop': 10})
def g008(df): return _g008(df)

# g009  Stock Price Prediction Using Technical Indicators  (template: macd)
_g009 = build('macd', {'fast': 12, 'slow': 26, 'signal': 9})
def g009(df): return _g009(df)

# g010  DCA Pop  (template: bollinger)
_g010 = build('bollinger', {'n': 20, 'k': 2.0, 'rsi_n': 14, 'rsi_lower': 30.0, 'rsi_upper': 70.0, 'time_stop': 0})
def g010(df): return _g010(df)

# g011  Hyperliquid Liquidation Scalping with SMA/Standard Deviation  (template: bollinger)
_g011 = build('bollinger', {'n': 15, 'k': 2.0, 'rsi_n': 14, 'rsi_lower': 30.0, 'rsi_upper': 70.0, 'time_stop': 10})
def g011(df): return _g011(df)

# g012  Moving Average Crossover  (template: ma_crossover)
_g012 = build('ma_crossover', {'fast': 5, 'slow': 20, 'ma': 'sma'})
def g012(df): return _g012(df)

# g013  Breakout Strategy  (template: donchian_breakout)
_g013 = build('donchian_breakout', {'entry_n': 20, 'exit_n': 10})
def g013(df): return _g013(df)

# g014  SMA Crossover  (template: ma_crossover)
_g014 = build('ma_crossover', {'fast': 20, 'slow': 50, 'ma': 'sma'})
def g014(df): return _g014(df)

# g015  MACD Crossover Strategy  (template: macd)
_g015 = build('macd', {'fast': 12, 'slow': 26, 'signal': 9})
def g015(df): return _g015(df)

# g016  SMA Crossover Strategy  (template: ma_crossover)
_g016 = build('ma_crossover', {'fast': 50, 'slow': 100, 'ma': 'sma'})
def g016(df): return _g016(df)

# g017  RSI and MACD Buy/Sell Signal Strategy  (template: rsi_meanrev)
_g017 = build('rsi_meanrev', {'rsi_n': 14, 'lower': 40.0, 'upper': 60.0, 'sma_filter': 200, 'time_stop': 10})
def g017(df): return _g017(df)

# g018  RSI-Based Mean Reversion Strategy with 200-Day MA Filter  (template: rsi_meanrev)
_g018 = build('rsi_meanrev', {'rsi_n': 10, 'lower': 30.0, 'upper': 40, 'sma_filter': 200, 'time_stop': 10})
def g018(df): return _g018(df)

# g019  Least Squares Moving Average (LSMA) Trading Strategy  (template: lsma_meanrev)
_g019 = build('lsma_meanrev', {'n': 25})
def g019(df): return _g019(df)

# g020  SMA Bot for HIP-3 Stock Trading  (template: ma_crossover)
_g020 = build('ma_crossover', {'fast': 50, 'slow': 200, 'ma': 'sma'})
def g020(df): return _g020(df)

# g021  Bollinger Band Bounce Strategy  (template: bollinger)
_g021 = build('bollinger', {'n': 20, 'k': 2.0, 'rsi_n': 14, 'rsi_lower': 30, 'rsi_upper': 70, 'time_stop': 5})
def g021(df): return _g021(df)

# g022  RSI and Moving Average Mean Reversion  (template: rsi_meanrev)
_g022 = build('rsi_meanrev', {'rsi_n': 10, 'lower': 30.0, 'upper': 40, 'sma_filter': 200, 'time_stop': 10})
def g022(df): return _g022(df)

# g023  MACD Crossover Strategy  (template: macd)
_g023 = build('macd', {'fast': 12, 'slow': 26, 'signal': 9})
def g023(df): return _g023(df)

# g024  Bitcoin Breakout Trading Bot  (template: donchian_breakout)
_g024 = build('donchian_breakout', {'entry_n': 24, 'exit_n': 8})
def g024(df): return _g024(df)

# g025  Simple Moving Average Crossover Strategy  (template: ma_crossover)
_g025 = build('ma_crossover', {'fast': 2, 'slow': 100, 'ma': 'sma'})
def g025(df): return _g025(df)

# g026  Simple Moving Average Crossover  (template: ma_crossover)
_g026 = build('ma_crossover', {'fast': 10, 'slow': 20, 'ma': 'sma'})
def g026(df): return _g026(df)

# g027  Buy the Dip - 5 Bar Hold  (template: rsi_meanrev)
_g027 = build('rsi_meanrev', {'rsi_n': 2, 'lower': 20.0, 'upper': 80.0, 'sma_filter': 200, 'time_stop': 5})
def g027(df): return _g027(df)

# g028  Two Moving Average Crossover  (template: ma_crossover)
_g028 = build('ma_crossover', {'fast': 50, 'slow': 200, 'ma': 'sma'})
def g028(df): return _g028(df)

# g029  Grok Momentum-Based Day Trading Strategy  (free-form)
def g029(df):
    close = df['Close']
    high = df['High']
    low = df['Low']
    n = len(df)
    positions = pd.Series(0, index=df.index)
    momentum = close.pct_change() * 100
    in_trade = False
    entry_price = 0.0
    entry_bar = -1
    holding_period = 4
    profit_target_pct = 0.01
    stop_loss_pct = 0.01
    momentum_threshold = 0.5
    for i in range(1, n):
        if in_trade:
            profit_target_price = entry_price * (1 + profit_target_pct)
            stop_loss_price = entry_price * (1 - stop_loss_pct)
            bars_held = i - entry_bar
            if low.iloc[i] <= stop_loss_price:
                in_trade = False
                positions.iloc[i] = 0
            elif high.iloc[i] >= profit_target_price:
                in_trade = False
                positions.iloc[i] = 0
            elif bars_held >= holding_period:
                in_trade = False
                positions.iloc[i] = 0
            else:
                positions.iloc[i] = 1
        elif momentum.iloc[i] > momentum_threshold:
            in_trade = True
            entry_price = df['Open'].iloc[i]
            entry_bar = i
            positions.iloc[i] = 1
        else:
            positions.iloc[i] = 0
    return positions

# g030  Golden Cross Moving Average Strategy (EV Stocks)  (template: ma_crossover)
_g030 = build('ma_crossover', {'fast': 50, 'slow': 200, 'ma': 'sma'})
def g030(df): return _g030(df)

# g031  Swing Trader Pro  (template: ma_crossover)
_g031 = build('ma_crossover', {'fast': 2, 'slow': 5, 'ma': 'sma'})
def g031(df): return _g031(df)

# g032  Moving Average Crossover EA  (template: ma_crossover)
_g032 = build('ma_crossover', {'fast': 50, 'slow': 200, 'ma': 'sma'})
def g032(df): return _g032(df)

# g033  Simple Moving Average Crossover Strategy  (template: ma_crossover)
_g033 = build('ma_crossover', {'fast': 20, 'slow': 50, 'ma': 'sma'})
def g033(df): return _g033(df)

# g034  Moving Average Crossover Position Sizing  (template: ma_crossover)
_g034 = build('ma_crossover', {'fast': 2, 'slow': 5, 'ma': 'sma'})
def g034(df): return _g034(df)

# g035  SMA Crossover Strategy  (template: ma_crossover)
_g035 = build('ma_crossover', {'fast': 2, 'slow': 20, 'ma': 'sma'})
def g035(df): return _g035(df)

# g036  Bitcoin SMA Crossover Strategy  (template: ma_crossover)
_g036 = build('ma_crossover', {'fast': 20, 'slow': 40, 'ma': 'sma'})
def g036(df): return _g036(df)

# g037  Multi-Timeframe Trend-Following with Price Action  (template: donchian_breakout)
_g037 = build('donchian_breakout', {'entry_n': 20, 'exit_n': 10})
def g037(df): return _g037(df)

# g038  Mean Reversion with Bollinger Bands and RSI  (template: bollinger)
_g038 = build('bollinger', {'n': 20, 'k': 2.0, 'rsi_n': 14, 'rsi_lower': 30.0, 'rsi_upper': 70.0, 'time_stop': 10})
def g038(df): return _g038(df)

# g039  AI Swing Trade Analyzer  (template: donchian_breakout)
_g039 = build('donchian_breakout', {'entry_n': 20, 'exit_n': 10})
def g039(df): return _g039(df)

# g040  Multi-Asset Trend Following with Price Action  (template: ma_crossover)
_g040 = build('ma_crossover', {'fast': 20, 'slow': 50, 'ma': 'ema'})
def g040(df): return _g040(df)

STRATS = {"g001": g001, "g002": g002, "g003": g003, "g004": g004, "g006": g006, "g007": g007, "g008": g008, "g009": g009, "g010": g010, "g011": g011, "g012": g012, "g013": g013, "g014": g014, "g015": g015, "g016": g016, "g017": g017, "g018": g018, "g019": g019, "g020": g020, "g021": g021, "g022": g022, "g023": g023, "g024": g024, "g025": g025, "g026": g026, "g027": g027, "g028": g028, "g029": g029, "g030": g030, "g031": g031, "g032": g032, "g033": g033, "g034": g034, "g035": g035, "g036": g036, "g037": g037, "g038": g038, "g039": g039, "g040": g040}

MULTI = {
    "g005": {"fn": g005, "tickers": ['QQQ', 'BND'], "roles": ['risk', 'safe'], "benchmark": 'risk_asset'},
}

META = {
    "g001": {'name': 'Price Channel Breakout Strategy', 'family': 'donchian_breakout', 'method': 'template', 'params': {'entry_n': 20, 'exit_n': 20}, 'tickers': [], 'direction': 'long_flat', 'type': 'breakout', 'multi_asset': False, 'video_id': 'aMrKe4ndzCA', 'url': 'https://www.youtube.com/watch?v=aMrKe4ndzCA'},
    "g002": {'name': 'Stochastic Slow RSI MACD Strategy', 'family': 'stochastic', 'method': 'template', 'params': {'k_n': 14, 'lower': 20.0, 'upper': 80.0, 'sma_filter': 0, 'time_stop': 0}, 'tickers': [], 'direction': 'long_short', 'type': 'mean-reversion', 'multi_asset': False, 'video_id': 'r8pU-8l1KPU', 'url': 'https://www.youtube.com/watch?v=r8pU-8l1KPU'},
    "g003": {'name': 'Long-only Momentum Strategy with 200-day SMA Exit', 'family': 'ma_crossover', 'method': 'template', 'params': {'fast': 50, 'slow': 200, 'ma': 'sma'}, 'tickers': [], 'direction': 'long_flat', 'type': 'trend-following', 'multi_asset': False, 'video_id': 'unsa_gXPAJ4', 'url': 'https://www.youtube.com/watch?v=unsa_gXPAJ4'},
    "g004": {'name': '8 SMA and 25 SMA Crossover Strategy', 'family': 'ma_crossover', 'method': 'template', 'params': {'fast': 8, 'slow': 25, 'ma': 'sma'}, 'tickers': [], 'direction': 'long_short', 'type': 'trend-following', 'multi_asset': False, 'video_id': 'sYRCzSbvOpQ', 'url': 'https://www.youtube.com/watch?v=sYRCzSbvOpQ'},
    "g005": {'name': 'Dynamic Allocation Strategy (QQQ/BND)', 'family': 'allocation', 'method': 'template', 'params': {'sma_n': 30, 'on_risk_w': 0.8, 'off_risk_w': 0.2}, 'tickers': ['QQQ', 'BND'], 'direction': 'always_invested', 'type': 'allocation', 'multi_asset': True, 'video_id': '-F3ITjfelrM', 'url': 'https://www.youtube.com/watch?v=-F3ITjfelrM'},
    "g006": {'name': 'Linear Regression Mean Reversion Strategy', 'family': 'linreg_mr', 'method': 'template', 'params': {'n': 14, 'sma_filter': 200, 'allow_short': True}, 'tickers': [], 'direction': 'long_short', 'type': 'mean-reversion', 'multi_asset': False, 'video_id': 'qHISgnYkB7Y', 'url': 'https://www.youtube.com/watch?v=qHISgnYkB7Y'},
    "g007": {'name': 'Ray Natio RSI Moving Average Strategy', 'family': 'rsi_meanrev', 'method': 'template', 'params': {'rsi_n': 10, 'lower': 30.0, 'upper': 40, 'sma_filter': 200, 'time_stop': 10}, 'tickers': [], 'direction': 'long_flat', 'type': 'mean-reversion', 'multi_asset': False, 'video_id': 'rYfe9Bg2GcY', 'url': 'https://www.youtube.com/watch?v=rYfe9Bg2GcY'},
    "g008": {'name': 'Stochastic K + 200-day SMA Buy Limit Order Strategy', 'family': 'stochastic', 'method': 'template', 'params': {'k_n': 8, 'lower': 5.0, 'upper': 99, 'sma_filter': 200, 'time_stop': 10}, 'tickers': [], 'direction': 'long_flat', 'type': 'mean-reversion', 'multi_asset': False, 'video_id': 'nAfnAuvRpqE', 'url': 'https://www.youtube.com/watch?v=nAfnAuvRpqE'},
    "g009": {'name': 'Stock Price Prediction Using Technical Indicators', 'family': 'macd', 'method': 'template', 'params': {'fast': 12, 'slow': 26, 'signal': 9}, 'tickers': [], 'direction': 'long_short', 'type': 'trend-following', 'multi_asset': False, 'video_id': 'CoqDzEmJAVo', 'url': 'https://www.youtube.com/watch?v=CoqDzEmJAVo'},
    "g010": {'name': 'DCA Pop', 'family': 'bollinger', 'method': 'template', 'params': {'n': 20, 'k': 2.0, 'rsi_n': 14, 'rsi_lower': 30.0, 'rsi_upper': 70.0, 'time_stop': 0}, 'tickers': [], 'direction': 'long_flat', 'type': 'mean-reversion', 'multi_asset': False, 'video_id': 'YQGp7Fk2X3E', 'url': 'https://www.youtube.com/watch?v=YQGp7Fk2X3E'},
    "g011": {'name': 'Hyperliquid Liquidation Scalping with SMA/Standard Deviation', 'family': 'bollinger', 'method': 'template', 'params': {'n': 15, 'k': 2.0, 'rsi_n': 14, 'rsi_lower': 30.0, 'rsi_upper': 70.0, 'time_stop': 10}, 'tickers': [], 'direction': 'long_short', 'type': 'mean-reversion', 'multi_asset': False, 'video_id': 'RKku3SLPsQ4', 'url': 'https://www.youtube.com/watch?v=RKku3SLPsQ4'},
    "g012": {'name': 'Moving Average Crossover', 'family': 'ma_crossover', 'method': 'template', 'params': {'fast': 5, 'slow': 20, 'ma': 'sma'}, 'tickers': [], 'direction': 'long_flat', 'type': 'trend-following', 'multi_asset': False, 'video_id': 'b3VFMdjBfKA', 'url': 'https://www.youtube.com/watch?v=b3VFMdjBfKA'},
    "g013": {'name': 'Breakout Strategy', 'family': 'donchian_breakout', 'method': 'template', 'params': {'entry_n': 20, 'exit_n': 10}, 'tickers': [], 'direction': 'long_short', 'type': 'breakout', 'multi_asset': False, 'video_id': 'Z7MA_68HmF0', 'url': 'https://www.youtube.com/watch?v=Z7MA_68HmF0'},
    "g014": {'name': 'SMA Crossover', 'family': 'ma_crossover', 'method': 'template', 'params': {'fast': 20, 'slow': 50, 'ma': 'sma'}, 'tickers': [], 'direction': 'long_flat', 'type': 'trend-following', 'multi_asset': False, 'video_id': '-ZnO4ldUwAA', 'url': 'https://www.youtube.com/watch?v=-ZnO4ldUwAA'},
    "g015": {'name': 'MACD Crossover Strategy', 'family': 'macd', 'method': 'template', 'params': {'fast': 12, 'slow': 26, 'signal': 9}, 'tickers': [], 'direction': 'long_flat', 'type': 'trend-following', 'multi_asset': False, 'video_id': 'E3KP1WyLITY', 'url': 'https://www.youtube.com/watch?v=E3KP1WyLITY'},
    "g016": {'name': 'SMA Crossover Strategy', 'family': 'ma_crossover', 'method': 'template', 'params': {'fast': 50, 'slow': 100, 'ma': 'sma'}, 'tickers': [], 'direction': 'long_flat', 'type': 'trend-following', 'multi_asset': False, 'video_id': 'pt4auu_ZPm4', 'url': 'https://www.youtube.com/watch?v=pt4auu_ZPm4'},
    "g017": {'name': 'RSI and MACD Buy/Sell Signal Strategy', 'family': 'rsi_meanrev', 'method': 'template', 'params': {'rsi_n': 14, 'lower': 40.0, 'upper': 60.0, 'sma_filter': 200, 'time_stop': 10}, 'tickers': [], 'direction': 'long_flat', 'type': 'mean-reversion', 'multi_asset': False, 'video_id': 'e-tEfBzLyg8', 'url': 'https://www.youtube.com/watch?v=e-tEfBzLyg8'},
    "g018": {'name': 'RSI-Based Mean Reversion Strategy with 200-Day MA Filter', 'family': 'rsi_meanrev', 'method': 'template', 'params': {'rsi_n': 10, 'lower': 30.0, 'upper': 40, 'sma_filter': 200, 'time_stop': 10}, 'tickers': [], 'direction': 'long_flat', 'type': 'mean-reversion', 'multi_asset': False, 'video_id': 'pB8eJwg7LJU', 'url': 'https://www.youtube.com/watch?v=pB8eJwg7LJU'},
    "g019": {'name': 'Least Squares Moving Average (LSMA) Trading Strategy', 'family': 'lsma_meanrev', 'method': 'template', 'params': {'n': 25}, 'tickers': [], 'direction': 'long_flat', 'type': 'mean-reversion', 'multi_asset': False, 'video_id': 'sESQpRoo994', 'url': 'https://www.youtube.com/watch?v=sESQpRoo994'},
    "g020": {'name': 'SMA Bot for HIP-3 Stock Trading', 'family': 'ma_crossover', 'method': 'template', 'params': {'fast': 50, 'slow': 200, 'ma': 'sma'}, 'tickers': [], 'direction': 'long_flat', 'type': 'trend-following', 'multi_asset': False, 'video_id': 'PdmdT0uMGj8', 'url': 'https://www.youtube.com/watch?v=PdmdT0uMGj8'},
    "g021": {'name': 'Bollinger Band Bounce Strategy', 'family': 'bollinger', 'method': 'template', 'params': {'n': 20, 'k': 2.0, 'rsi_n': 14, 'rsi_lower': 30, 'rsi_upper': 70, 'time_stop': 5}, 'tickers': [], 'direction': 'long_flat', 'type': 'mean-reversion', 'multi_asset': False, 'video_id': '5_L-71Fzupc', 'url': 'https://www.youtube.com/watch?v=5_L-71Fzupc'},
    "g022": {'name': 'RSI and Moving Average Mean Reversion', 'family': 'rsi_meanrev', 'method': 'template', 'params': {'rsi_n': 10, 'lower': 30.0, 'upper': 40, 'sma_filter': 200, 'time_stop': 10}, 'tickers': [], 'direction': 'long_flat', 'type': 'mean-reversion', 'multi_asset': False, 'video_id': '5KKildyGBeo', 'url': 'https://www.youtube.com/watch?v=5KKildyGBeo'},
    "g023": {'name': 'MACD Crossover Strategy', 'family': 'macd', 'method': 'template', 'params': {'fast': 12, 'slow': 26, 'signal': 9}, 'tickers': [], 'direction': 'long_flat', 'type': 'trend-following', 'multi_asset': False, 'video_id': 'JzdVPnCSSuo', 'url': 'https://www.youtube.com/watch?v=JzdVPnCSSuo'},
    "g024": {'name': 'Bitcoin Breakout Trading Bot', 'family': 'donchian_breakout', 'method': 'template', 'params': {'entry_n': 24, 'exit_n': 8}, 'tickers': [], 'direction': 'long_short', 'type': 'breakout', 'multi_asset': False, 'video_id': 'v5qTYnMiUw4', 'url': 'https://www.youtube.com/watch?v=v5qTYnMiUw4'},
    "g025": {'name': 'Simple Moving Average Crossover Strategy', 'family': 'ma_crossover', 'method': 'template', 'params': {'fast': 2, 'slow': 100, 'ma': 'sma'}, 'tickers': [], 'direction': 'long_flat', 'type': 'trend-following', 'multi_asset': False, 'video_id': 'Ets0xGCjQ14', 'url': 'https://www.youtube.com/watch?v=Ets0xGCjQ14'},
    "g026": {'name': 'Simple Moving Average Crossover', 'family': 'ma_crossover', 'method': 'template', 'params': {'fast': 10, 'slow': 20, 'ma': 'sma'}, 'tickers': [], 'direction': 'long_flat', 'type': 'trend-following', 'multi_asset': False, 'video_id': '4YmRpo60kow', 'url': 'https://www.youtube.com/watch?v=4YmRpo60kow'},
    "g027": {'name': 'Buy the Dip - 5 Bar Hold', 'family': 'rsi_meanrev', 'method': 'template', 'params': {'rsi_n': 2, 'lower': 20.0, 'upper': 80.0, 'sma_filter': 200, 'time_stop': 5}, 'tickers': [], 'direction': 'long_flat', 'type': 'mean-reversion', 'multi_asset': False, 'video_id': 'K8buXUxEfMc', 'url': 'https://www.youtube.com/watch?v=K8buXUxEfMc'},
    "g028": {'name': 'Two Moving Average Crossover', 'family': 'ma_crossover', 'method': 'template', 'params': {'fast': 50, 'slow': 200, 'ma': 'sma'}, 'tickers': [], 'direction': 'long_flat', 'type': 'trend-following', 'multi_asset': False, 'video_id': '29_FVmMtDWw', 'url': 'https://www.youtube.com/watch?v=29_FVmMtDWw'},
    "g029": {'name': 'Grok Momentum-Based Day Trading Strategy', 'family': None, 'method': 'freeform', 'params': {}, 'tickers': [], 'direction': 'long_flat', 'type': 'momentum', 'multi_asset': False, 'video_id': 'BZUT9YctnII', 'url': 'https://www.youtube.com/watch?v=BZUT9YctnII'},
    "g030": {'name': 'Golden Cross Moving Average Strategy (EV Stocks)', 'family': 'ma_crossover', 'method': 'template', 'params': {'fast': 50, 'slow': 200, 'ma': 'sma'}, 'tickers': [], 'direction': 'long_flat', 'type': 'trend-following', 'multi_asset': False, 'video_id': '6FQz7MDTogs', 'url': 'https://www.youtube.com/watch?v=6FQz7MDTogs'},
    "g031": {'name': 'Swing Trader Pro', 'family': 'ma_crossover', 'method': 'template', 'params': {'fast': 2, 'slow': 5, 'ma': 'sma'}, 'tickers': [], 'direction': 'long_short', 'type': 'trend-following', 'multi_asset': False, 'video_id': 'duvMrFqb2Nw', 'url': 'https://www.youtube.com/watch?v=duvMrFqb2Nw'},
    "g032": {'name': 'Moving Average Crossover EA', 'family': 'ma_crossover', 'method': 'template', 'params': {'fast': 50, 'slow': 200, 'ma': 'sma'}, 'tickers': [], 'direction': 'long_short', 'type': 'trend-following', 'multi_asset': False, 'video_id': 'xK_yac8QF-I', 'url': 'https://www.youtube.com/watch?v=xK_yac8QF-I'},
    "g033": {'name': 'Simple Moving Average Crossover Strategy', 'family': 'ma_crossover', 'method': 'template', 'params': {'fast': 20, 'slow': 50, 'ma': 'sma'}, 'tickers': [], 'direction': 'long_flat', 'type': 'trend-following', 'multi_asset': False, 'video_id': 'J3VEniAKg5A', 'url': 'https://www.youtube.com/watch?v=J3VEniAKg5A'},
    "g034": {'name': 'Moving Average Crossover Position Sizing', 'family': 'ma_crossover', 'method': 'template', 'params': {'fast': 2, 'slow': 5, 'ma': 'sma'}, 'tickers': [], 'direction': 'long_flat', 'type': 'trend-following', 'multi_asset': False, 'video_id': 'eqmoQNQNZgo', 'url': 'https://www.youtube.com/watch?v=eqmoQNQNZgo'},
    "g035": {'name': 'SMA Crossover Strategy', 'family': 'ma_crossover', 'method': 'template', 'params': {'fast': 2, 'slow': 20, 'ma': 'sma'}, 'tickers': [], 'direction': 'long_flat', 'type': 'trend-following', 'multi_asset': False, 'video_id': 'j6K-pyF1hdI', 'url': 'https://www.youtube.com/watch?v=j6K-pyF1hdI'},
    "g036": {'name': 'Bitcoin SMA Crossover Strategy', 'family': 'ma_crossover', 'method': 'template', 'params': {'fast': 20, 'slow': 40, 'ma': 'sma'}, 'tickers': [], 'direction': 'long_flat', 'type': 'trend-following', 'multi_asset': False, 'video_id': 'QLYmpGlZpG0', 'url': 'https://www.youtube.com/watch?v=QLYmpGlZpG0'},
    "g037": {'name': 'Multi-Timeframe Trend-Following with Price Action', 'family': 'donchian_breakout', 'method': 'template', 'params': {'entry_n': 20, 'exit_n': 10}, 'tickers': [], 'direction': 'long_short', 'type': 'breakout', 'multi_asset': False, 'video_id': '4r55Vo-mOM8', 'url': 'https://www.youtube.com/watch?v=4r55Vo-mOM8'},
    "g038": {'name': 'Mean Reversion with Bollinger Bands and RSI', 'family': 'bollinger', 'method': 'template', 'params': {'n': 20, 'k': 2.0, 'rsi_n': 14, 'rsi_lower': 30.0, 'rsi_upper': 70.0, 'time_stop': 10}, 'tickers': [], 'direction': 'long_flat', 'type': 'mean-reversion', 'multi_asset': False, 'video_id': 's3XJ0SbME7k', 'url': 'https://www.youtube.com/watch?v=s3XJ0SbME7k'},
    "g039": {'name': 'AI Swing Trade Analyzer', 'family': 'donchian_breakout', 'method': 'template', 'params': {'entry_n': 20, 'exit_n': 10}, 'tickers': [], 'direction': 'long_flat', 'type': 'breakout', 'multi_asset': False, 'video_id': '86ZpQn85nCc', 'url': 'https://www.youtube.com/watch?v=86ZpQn85nCc'},
    "g040": {'name': 'Multi-Asset Trend Following with Price Action', 'family': 'ma_crossover', 'method': 'template', 'params': {'fast': 20, 'slow': 50, 'ma': 'ema'}, 'tickers': [], 'direction': 'long_short', 'type': 'trend-following', 'multi_asset': False, 'video_id': 'MnG2Ru_LVEw', 'url': 'https://www.youtube.com/watch?v=MnG2Ru_LVEw'},
}
