#!/usr/bin/env python3
"""
working_strategies_crypto.py  --  AUTO-GENERATED by crypto_backtest.py.
Strategies that SURVIVED out-of-sample backtesting ON HYPERLIQUID CRYPTO
(BTC/ETH/SOL daily, 5bps/trade + 10% APR funding, 60/40 split).

This is the crypto re-validation required by agent_strategies_rules.json
guardrail #1. These -- NOT the US-equity survivors in working_strategies.py --
are the strategies cleared to advance to the live Hyperliquid agent.

Two tiers:
  BEATS_BUYHOLD : beat buy&hold BTC/ETH/SOL OOS net return (majority of basket).
  ROBUST        : positive OOS on EVERY coin AND mean OOS Sharpe >= 0.65.
Research tool, not financial advice.
"""
from generated_strats import STRATS as _SINGLE, MULTI as _MULTI, META

# [BEATS-B&H] g001 (Price Channel Breakout Strategy): beats-B&H 2/3, positive 1/3, avg OOS return -12.4%, avg OOS Sharpe 0.07, avg OOS MaxDD -53.2%
# [BEATS-B&H] g002 (Stochastic Slow RSI MACD Strategy): beats-B&H 2/3, positive 0/3, avg OOS return -8.6%, avg OOS Sharpe 0.15, avg OOS MaxDD -50.2%
# [BEATS-B&H] g004 (8 SMA and 25 SMA Crossover Strategy): beats-B&H 2/3, positive 2/3, avg OOS return -2.1%, avg OOS Sharpe 0.20, avg OOS MaxDD -49.1%
# [BEATS-B&H + ROBUST] g007 (Ray Natio RSI Moving Average Strategy): beats-B&H 2/3, positive 3/3, avg OOS return 23.1%, avg OOS Sharpe 0.78, avg OOS MaxDD -8.3%
# [BEATS-B&H + ROBUST] g008 (Stochastic K + 200-day SMA Buy Limit Order Strategy): beats-B&H 2/3, positive 3/3, avg OOS return 27.3%, avg OOS Sharpe 0.67, avg OOS MaxDD -14.7%
# [BEATS-B&H] g009 (Stock Price Prediction Using Technical Indicators): beats-B&H 2/3, positive 1/3, avg OOS return -8.1%, avg OOS Sharpe 0.16, avg OOS MaxDD -52.8%
# [BEATS-B&H] g011 (Hyperliquid Liquidation Scalping with SMA/Standard Deviation): beats-B&H 2/3, positive 0/3, avg OOS return -28.5%, avg OOS Sharpe -0.39, avg OOS MaxDD -44.4%
# [BEATS-B&H] g012 (Moving Average Crossover): beats-B&H 2/3, positive 2/3, avg OOS return -3.3%, avg OOS Sharpe 0.19, avg OOS MaxDD -44.9%
# [BEATS-B&H] g015 (MACD Crossover Strategy): beats-B&H 2/3, positive 1/3, avg OOS return -8.1%, avg OOS Sharpe 0.16, avg OOS MaxDD -52.8%
# [BEATS-B&H] g016 (SMA Crossover Strategy): beats-B&H 2/3, positive 1/3, avg OOS return -0.5%, avg OOS Sharpe 0.23, avg OOS MaxDD -43.7%
# [BEATS-B&H] g017 (RSI and MACD Buy/Sell Signal Strategy): beats-B&H 2/3, positive 3/3, avg OOS return 11.2%, avg OOS Sharpe 0.30, avg OOS MaxDD -28.4%
# [BEATS-B&H + ROBUST] g018 (RSI-Based Mean Reversion Strategy with 200-Day MA Filter): beats-B&H 2/3, positive 3/3, avg OOS return 23.1%, avg OOS Sharpe 0.78, avg OOS MaxDD -8.3%
# [BEATS-B&H] g021 (Bollinger Band Bounce Strategy): beats-B&H 2/3, positive 0/3, avg OOS return -22.2%, avg OOS Sharpe -0.45, avg OOS MaxDD -35.5%
# [BEATS-B&H + ROBUST] g022 (RSI and Moving Average Mean Reversion): beats-B&H 2/3, positive 3/3, avg OOS return 23.1%, avg OOS Sharpe 0.78, avg OOS MaxDD -8.3%
# [BEATS-B&H] g023 (MACD Crossover Strategy): beats-B&H 2/3, positive 1/3, avg OOS return -8.1%, avg OOS Sharpe 0.16, avg OOS MaxDD -52.8%
# [BEATS-B&H] g024 (Bitcoin Breakout Trading Bot): beats-B&H 2/3, positive 1/3, avg OOS return -12.9%, avg OOS Sharpe -0.01, avg OOS MaxDD -47.0%
# [BEATS-B&H] g025 (Simple Moving Average Crossover Strategy): beats-B&H 2/3, positive 1/3, avg OOS return -6.5%, avg OOS Sharpe 0.14, avg OOS MaxDD -51.7%
# [BEATS-B&H] g026 (Simple Moving Average Crossover): beats-B&H 2/3, positive 1/3, avg OOS return -18.3%, avg OOS Sharpe 0.02, avg OOS MaxDD -54.4%
# [BEATS-B&H] g035 (SMA Crossover Strategy): beats-B&H 2/3, positive 1/3, avg OOS return -2.8%, avg OOS Sharpe 0.17, avg OOS MaxDD -49.9%
# [BEATS-B&H] g036 (Bitcoin SMA Crossover Strategy): beats-B&H 2/3, positive 2/3, avg OOS return 3.5%, avg OOS Sharpe 0.24, avg OOS MaxDD -48.6%
# [BEATS-B&H] g038 (Mean Reversion with Bollinger Bands and RSI): beats-B&H 2/3, positive 0/3, avg OOS return -27.3%, avg OOS Sharpe -0.36, avg OOS MaxDD -43.5%
# [BEATS-B&H] g040 (Multi-Asset Trend Following with Price Action): beats-B&H 2/3, positive 1/3, avg OOS return -11.0%, avg OOS Sharpe 0.11, avg OOS MaxDD -50.7%

# Tier 1: beat buy&hold OOS net return (majority of BTC/ETH/SOL).
BEATS_BUYHOLD = {
    "g001": _SINGLE["g001"],
    "g002": _SINGLE["g002"],
    "g004": _SINGLE["g004"],
    "g007": _SINGLE["g007"],
    "g008": _SINGLE["g008"],
    "g009": _SINGLE["g009"],
    "g011": _SINGLE["g011"],
    "g012": _SINGLE["g012"],
    "g015": _SINGLE["g015"],
    "g016": _SINGLE["g016"],
    "g017": _SINGLE["g017"],
    "g018": _SINGLE["g018"],
    "g021": _SINGLE["g021"],
    "g022": _SINGLE["g022"],
    "g023": _SINGLE["g023"],
    "g024": _SINGLE["g024"],
    "g025": _SINGLE["g025"],
    "g026": _SINGLE["g026"],
    "g035": _SINGLE["g035"],
    "g036": _SINGLE["g036"],
    "g038": _SINGLE["g038"],
    "g040": _SINGLE["g040"],
}

# Tier 2: standalone-robust on crypto (positive everywhere, mean OOS Sharpe >= 0.65).
ROBUST = {
    "g007": _SINGLE["g007"],
    "g008": _SINGLE["g008"],
    "g018": _SINGLE["g018"],
    "g022": _SINGLE["g022"],
}

# Combined registry of crypto survivors -> live Hyperliquid agent.
STRATS = {**BEATS_BUYHOLD, **ROBUST}
