#!/usr/bin/env python3
"""
working_strategies.py  --  AUTO-GENERATED by run_backtests.py.
The strategies that SURVIVED honest out-of-sample backtesting (after
5bps/trade costs, 60/40 split, basket of SPY/QQQ/AAPL/MSFT/GOOGL).

Two honest tiers:
  BEATS_BUYHOLD : beat buy&hold OOS net return on a majority of the basket.
                  (A very high bar in the 2015-2025 bull market.)
  ROBUST        : positive OOS net return on EVERY tested ticker AND mean
                  OOS Sharpe >= 0.65. Stands on its own for an active agent,
                  even where it does not out-run a buy&hold benchmark.

Each single-ticker strategy is a position function: df -> Series
(1=long, 0=flat, -1=short), drop-in for 04_backtest.py. S11/S12 are
multi-ticker and live in extras_backtest.py; if they survived they are
listed in the registries below (value None) but not redefined here.

These are the candidates that advance to Stage 6 (code as agent rules).
Research tool, not financial advice.
"""
import numpy as np, pandas as pd

from catalog_strats import _rsi, _lsma

# [ROBUST] s02: beats-B&H 0/5, positive 5/5, avg OOS return 75.7%, avg OOS Sharpe 0.80, avg OOS MaxDD -25.1%
def s02_sma_cross(df):
    f = df["Close"].rolling(50).mean(); s = df["Close"].rolling(200).mean()
    return (f > s).astype(float)

# [ROBUST] s06: beats-B&H 0/5, positive 5/5, avg OOS return 62.2%, avg OOS Sharpe 0.78, avg OOS MaxDD -22.5%
def s06_lsma(df):
    return (df["Close"] < _lsma(df["Close"], 25)).astype(float)

# [ROBUST] s10: beats-B&H 0/5, positive 5/5, avg OOS return 38.4%, avg OOS Sharpe 0.66, avg OOS MaxDD -20.0%
def s10_breakout(df, n=20, exit_n=10):
    hh = df["High"].rolling(n).max().shift(1)
    ll = df["Low"].rolling(exit_n).min().shift(1)
    entry = (df["Close"] > hh).fillna(False).values
    ex    = (df["Close"] < ll).fillna(False).values
    pos = np.zeros(len(df)); st = 0
    for i in range(len(df)):
        if st == 0 and entry[i]: st = 1
        elif st == 1 and ex[i]: st = 0
        pos[i] = st
    return pd.Series(pos, index=df.index)

# Tier 1: beat buy&hold OOS net return (majority of basket).
BEATS_BUYHOLD = {
    "s12": None,   # multi-ticker -> extras_backtest.py
}

# Tier 2: standalone-robust (positive everywhere, mean OOS Sharpe >= 0.65).
ROBUST = {
    "s02": s02_sma_cross,
    "s06": s06_lsma,
    "s10": s10_breakout,
    "s11": None,   # multi-ticker -> extras_backtest.py
}

# Combined registry of everything that survived -> next stage.
STRATS = {**BEATS_BUYHOLD, **ROBUST}
